package main

func PrintOutline() {
	outline("http://gopl.io")
}

func ExamplePrintOutline() {
	PrintOutline()
	// Output:
	// <html>
	//   <head>
	//     <meta>
	//     </meta>
	//     <title>
	//     </title>
	//     <script>
	//     </script>
	//     <link>
	//     </link>
	//     <style>
	//     </style>
	//   </head>
	//   <body>
	//     <table>
	//       <tbody>
	//         <tr>
	//           <td>
	//             <a>
	//               <img>
	//               </img>
	//             </a>
	//             <br>
	//             </br>
	//             <div>
	//               <a>
	//                 <img>
	//                 </img>
	//               </a>
	//               <a>
	//                 <img>
	//                 </img>
	//               </a>
	//               <a>
	//                 <img>
	//                 </img>
	//               </a>
	//             </div>
	//             <br>
	//             </br>
	//           </td>
	//           <td>
	//             <h1>
	//             </h1>
	//             <p>
	//               <br>
	//               </br>
	//               <br>
	//               </br>
	//               <br>
	//               </br>
	//               <tt>
	//               </tt>
	//               <tt>
	//               </tt>
	//               <tt>
	//               </tt>
	//             </p>
	//             <div>
	//               <table>
	//                 <tbody>
	//                   <tr>
	//                     <td>
	//                       <h1>
	//                         <a>
	//                         </a>
	//                       </h1>
	//                       <h1>
	//                         <a>
	//                         </a>
	//                       </h1>
	//                       <h1>
	//                         <a>
	//                         </a>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                     </td>
	//                     <td>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                       </h1>
	//                       <h1>
	//                         <a>
	//                         </a>
	//                       </h1>
	//                     </td>
	//                   </tr>
	//                   <tr>
	//                     <td>
	//                       <h1>
	//                         <a>
	//                         </a>
	//                         <a>
	//                         </a>
	//                         <a>
	//                         </a>
	//                         <a>
	//                         </a>
	//                       </h1>
	//                     </td>
	//                   </tr>
	//                 </tbody>
	//               </table>
	//             </div>
	//             <p>
	//               <a>
	//                 <code>
	//                 </code>
	//               </a>
	//               <a>
	//                 <code>
	//                 </code>
	//               </a>
	//               <a>
	//                 <code>
	//                 </code>
	//               </a>
	//               <a>
	//                 <code>
	//                 </code>
	//               </a>
	//             </p>
	//             <p>
	//               <a>
	//               </a>
	//               <a>
	//               </a>
	//             </p>
	//           </td>
	//         </tr>
	//       </tbody>
	//     </table>
	//   </body>
	// </html>
}
